version: '3.8'
services:
  web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ../apps/web:/app
    depends_on:
      - api
  api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ../apps/api:/app
    env_file:
      - ../.env
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
