# Docker Compose Configuration
# Defines three services:
# - web: Frontend Vite application (port 5173)
# - api: Backend Express API (port 5000)
# - mongo: MongoDB database (port 27017)

services:
  base:
    build:
      context: ../
      dockerfile: docker/base.Dockerfile
    image: storynest/base:latest

  web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ../apps/web/src:/app/apps/web/src
    depends_on:
      - api
      - base

  api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ../apps/api/src:/app/apps/api/src
    env_file:
      - ../.env
    depends_on:
      - mongo
      - base

  mongo:
    container_name: 'mongo'
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
